### ISSUE TITLE
BE_ExecuteSystemCommand behavior change

### ISSUE THREAD

**Issue by jwillinghalpern** [GoyaPtyLtd/BaseElements-Plugin#181] opened 2019-10-31 00:09 UTC
@nickorr you asked for a simple example of something that used to work and doesn't anymore: https://github.com/GoyaPtyLtd/BaseElements-Plugin/issues/180#issuecomment-548156576

Here are three simple commands where this is the case:

`echo hi > /Users/brotherjoshua/Desktop/BE_ExecuteSystemCommand\ Bug/output.txt`
* v4.0.5 outputs "hi" to a file called output.txt
* v4.1.2 returns the following as the plugin function result and does _not_ write to a file: "hi > /Users/brotherjoshua/Desktop/BE_ExecuteSystemCommand Bug/output.txt
"

`echo test | tee /Users/brotherjoshua/test.txt`
* v4.0.5 returns "test" to FM _and_ writes "test" to the file test.txt
* v4.1.2 returns this as the plugin function result: "test | tee /Users/brotherjoshua/test.txt
"

`sleep 2 ; touch /Users/brotherjoshua/Desktop/BE_ExecuteSystemCommand\ Bug/touch.txt`
* v4.0.5 returns empty to FM and creates (touches) the file touch.txt
* v4.1.2 returns the following as the function result and does not create touch.txt: "usage: sleep seconds
"

The sleep example is interesting because it shows how all the words after "sleep" are being interpreted as arguments of the sleep command. Notice how it's telling me how to use `sleep` correctly.

I tested on FM 18, Mac OSX Mojave. By the way, I should mention that all these commands work as expected in v4.1.2 if I write them like `/bin/bash -c "echo test | tee /Users/brotherjoshua/test.txt"`. If you prefer the new behavior you might wanna update the docs to encourage this syntax for mac users.

@dansmith65 did a little digging in the code and we think it has something to do with the way the new code is parsing the command, using the first arg as the command and the remaining part as the arguments. He might have more insight.

**Comment by nickorr** [comment] 2019-10-31 01:16
Ok, thanks, leave it with me.

Cheers,
Nick

**Comment by jwillinghalpern** [comment] 2019-11-16 20:50
I also found that using 4.1.2, `BE_ExecuteSystemCommand ( "" )` crashes FileMaker. 4.0.5 does not.

**Comment by nickorr** [comment] 2019-11-18 03:34
Yes, I can confirm this crash, obviously it shouldn't, we'll get onto it.

Cheers,
Nick

**Comment by nickorr** [comment] 2019-11-19 00:14
The crash is fixed in our dev version and will be in the next release.  We're working through some options to get the old BE_ExecuteSystemCommand behaviour back.  Not sure what yet though.

Cheers,
Nick

**Comment by jwillinghalpern** [comment] 2019-11-19 00:42
> The crash is fixed

Wooooo! You're amazing.

**Comment by nickorr** [comment] 2020-05-06 05:33
Sorry this took a while to get out :(  New builds :

https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmplugin.zip
https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmx64.zip

Let me know how you go.

Cheers,
Nick

**Comment by jlgill** [comment] 2020-05-10 21:57
Currently trying to get BE_ExecuteSystemCommand to work on windows 10 build 18362.778 and I cannot get it to return anything except for '?' using the demo examples that you have listed on your site.  

I haven't really had a need for BE_ExecuteSystemCommand before however I don't think that its an id10t error since its failing even using the examples in the docs.  Running the latest release 4.1.3.

**Comment by nickorr** [comment] 2020-05-10 23:20
James,

This is working fine for me in FMP 18 on Windows 10, and the 4.1.3 build :

BE_ExecuteSystemCommand ( "cmd.exe /c dir" )

What commands are you trying?

Cheers,
Nick

**Comment by jlgill** [comment] 2020-05-11 00:34
Literally the command you posted.  If I run it without a timeout it will crash FileMaker, however if I put a timeout it returns '?' immediately, even if the timeout is something like 10 seconds.

**Comment by nickorr** [comment] 2020-05-11 01:19
James,

The process for BE_ExecuteSystemCommand didn't change on windows between 4.1.2 and .3.  What happens with 4.1.2?

Was this working before?

Is this on FileMaker Pro or Server?

Cheers,
Nick

**Comment by nickorr** [comment] 2020-05-11 03:14
Also when you get a ? what is the error returned on the Last Error function?

Cheers,
Nick

**Comment by jlgill** [comment] 2022-03-08 23:47
When passing any timeout other than "-1" I get a 12000 error from the BE_GetLastError command

**Comment by nickorr** [comment] 2022-03-09 00:27
James, is this a followup to the previous issue, or is this with a different command?  Can you tell me exactly what the function call is?

**Comment by jlgill** [comment] 2022-03-09 00:36
Basically if I pass any timeout parameter into the BE_ExecuteSystemCommand
function other than -1 (or leaving it empty) the command returns '?' with a
12000 result for the last error.

I am having a different issue however when attempting to output text into a
file where BE is returning a 'Access Denied' error with no error in
BE_GetLastError.  I think that is a different issue though but I was
planning on opening a bug report for it.

**Comment by nickorr** [comment] 2022-03-09 00:48
That's not what I'm seeing.  : 

BE_ExecuteSystemCommand ( "ls -al" ; 10000 ) & "¶¶" & BE_GetLastError

total 10
drwxr-xr-x   20 root  wheel   640 Feb  7 08:22 .
drwxr-xr-x   20 root  wheel   640 Feb  7 08:22 ..
lrwxr-xr-x    1 root  admin    36 Feb  7 08:22 .VolumeIcon.icns -> System/Volumes/Data/.VolumeIcon.icns
----------    1 root  admin     0 Feb  7 08:22 .file
drwxr-xr-x    2 root  wheel    64 Feb  7 08:22 .vol
drwxrwxr-x  115 root  admin  3680 Mar  4 10:31 Applications
drwxr-xr-x   73 root  wheel  2336 Feb 13 11:06 Library
drwxr-xr-x@   9 root  wheel   288 Feb  7 08:22 System
drwxr-xr-x    5 root  admin   160 Feb  7 08:22 Users
drwxr-xr-x   13 root  wheel   416 Mar  9 10:39 Volumes
drwxr-xr-x@  38 root  wheel  1216 Feb  7 08:22 bin
drwxr-xr-x    2 root  wheel    64 Jun  6  2020 cores
dr-xr-xr-x    3 root  wheel  5106 Mar  5 09:16 dev
lrwxr-xr-x@   1 root  wheel    11 Feb  7 08:22 etc -> private/etc
lrwxr-xr-x    1 root  wheel    25 Mar  5 09:17 home -> /System/Volumes/Data/home
drwxr-xr-x    2 root  wheel    64 Jun  6  2020 opt
drwxr-xr-x    6 root  wheel   192 Feb  7 08:22 private
drwxr-xr-x@  65 root  wheel  2080 Feb  7 08:22 sbin
lrwxr-xr-x@   1 root  wheel    11 Feb  7 08:22 tmp -> private/tmp
drwxr-xr-x@  11 root  wheel   352 Feb  7 08:22 usr
lrwxr-xr-x@   1 root  wheel    11 Feb  7 08:22 var -> private/var


0

**Comment by nickorr** [comment] 2022-03-09 00:48
BE_Version = 4.2.2

**Comment by jlgill** [comment] 2022-03-09 00:52
I get this error for both commands

BE_ExecuteSystemCommand ( "cmd.exe /c dir" ; "500" ) & "¶¶" & BE_GetLastError
BE_ExecuteSystemCommand ( "dir" ; "500" ) & "¶¶" & BE_GetLastError


?

12000

**Comment by nickorr** [comment] 2022-03-16 05:00
Ok, new build of the plugin, which resolves an issue with BE_ExecuteSystemCommand where it could, on windows, sometimes return a result before the plugin had time to setup it's wait for the result ( only happened on some machines, one of our test ones was slow and so never saw it.  )

New builds in the downloads now, and also on dropbox for sponsors.

https://goya.com.au/files/beplugin/4.2.4/BaseElements.fmx64.zip

I'll close this issue, but open a new one if you notice any other issues.

Cheers,
Nick

**Closed by nickorr** 2022-03-16 05:00 UTC
